# USING NUMPY FOR DATA ANALYSIS EXERCISES

<hr/>

Q1. Import NumPy as np

In [2]:
import numpy as np

<hr>

Q2. Create an array of 10 zeros

In [3]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

<hr>

Q3. Create an array of 10 ones

In [4]:
arr1 = np.ones(10)
arr1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<hr>

Q4. Create an array of 10 fives

In [5]:
arr5 = 5*np.ones(10)
arr5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

<hr>

Q5. Create an array of the integers from 10 to 50

In [7]:
arint = np.arange(10,51)
arint

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

<hr>

Q6. Create an array of all the even integers from 10 to 50

In [8]:
arint_even = np.arange(10,51,2)
arint_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

<hr>

Q7. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arm = np.random.randint(0,9,9).reshape(3,3)
arm

array([[2, 7, 8],
       [1, 8, 4],
       [7, 5, 0]])

<hr>

Q8. Create a 3x3 identity matrix

In [12]:
iden = np.eye(3)
iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<hr>

Q9. Use NumPy to generate a random number between 0 and 1

In [14]:
ran = np.random.rand(1)
ran

array([0.14615714])

<hr>

Q10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [15]:
arn = np.random.randn(25)
arn

array([-0.57533317,  0.36837687,  0.71577283,  0.29062336,  1.26873331,
       -0.15359315,  1.31621336, -0.70680407,  0.30038168, -0.80521207,
       -0.02380543,  0.08956731,  0.0287833 ,  1.56228204,  0.91533863,
       -0.4248273 , -0.32324981, -0.35403484, -0.99225879,  0.53343764,
       -0.13849738, -1.31483402,  1.17014806, -0.82793832,  0.38547991])

<hr>

Q11. Create the following matrix:

In [17]:
mat = np.arange(0.01,1.01,0.01).reshape(10,10)
mat

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

<hr>

Q12. Create an array of 20 linearly spaced points between 0 and 1:

In [19]:
lin = np.linspace(0,1,20)
lin

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

<hr>

In [20]:
ar1 = np.arange(1,26).reshape(5,5)
ar1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

<hr>

In [21]:
ar2 = ar1[2:,1:]
ar2

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

<hr>

Q15. 20

In [23]:
ar3 = ar1[3,4]
ar3

20

<hr>

In [29]:
ar4 = ar1[0:3,1].reshape(3,1)
ar4

array([[ 2],
       [ 7],
       [12]])

<hr>

In [30]:
ar5 = ar1[4,:]
ar5

array([21, 22, 23, 24, 25])

<hr>

In [31]:
ar6 = ar1[3:,:]
ar6

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

<hr>

Q19. Get the sum of all the values in ar1

In [32]:
s = np.sum(ar1)
s

325

<hr>

Q20. Get the standard deviation of the values in ar1

In [33]:
st = np.std(ar1)
st

7.211102550927978

<hr>

Q21. Get the sum of all the columns in ar1

In [36]:
sc = np.sum(ar1,axis=0)
sc

array([55, 60, 65, 70, 75])